# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"InferenceCallback": "00_callbacks.ipynb"}

modules = ["callbacks.py"]

doc_url = "https://muellerzr.github.io/fastreinference/"

git_url = "https://github.com/muellerzr/fastreinference/tree/master/"

def custom_doc_links(name): return None
