# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DeviceType": "00_configure.ipynb",
         "get_default_device": "00_configure.ipynb",
         "ManagerType": "00_configure.ipynb",
         "InferenceConfiguration": "00_configure.ipynb",
         "Performer": "01_performer.ipynb",
         "SelfEnum": "99_utils.ipynb"}

modules = ["configure.py",
           "performer.py",
           "utils.py"]

doc_url = "https://muellerzr.github.io/fastreinference/"

git_url = "https://github.com/muellerzr/fastreinference/tree/master/"

def custom_doc_links(name): return None
